from typing import Any

import numpy as np
from _typeshed import Incomplete
from numpy.typing import NDArray as NDArray

_ONE_BYTE: int
_TWO_BYTE: int
_BYTE_SIZE: int
_ACCEPTED_CRC_TYPES: tuple[type[np.uint8], type[np.uint16], type[np.uint32]]
type CRCType = np.uint8 | np.uint16 | np.uint32

class COBSProcessor:
    _processor: CompiledCOBSProcessor
    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...
    def encode_payload(self, payload: NDArray[np.uint8]) -> NDArray[np.uint8]: ...
    def decode_payload(self, packet: NDArray[np.uint8]) -> NDArray[np.uint8]: ...
    @property
    def processor(self) -> CompiledCOBSProcessor: ...

class CRCProcessor:
    _processor: CompiledCRCProcessor
    def __init__(
        self, polynomial: CRCType, initial_crc_value: CRCType, final_xor_value: CRCType, *, reflected: bool = False
    ) -> None: ...
    def __repr__(self) -> str: ...
    def calculate_checksum(self, buffer: NDArray[np.uint8], check: bool) -> np.uint16: ...
    @property
    def crc_byte_length(self) -> np.uint8: ...
    @property
    def crc_table(self) -> NDArray[CRCType]: ...
    @property
    def processor(self) -> CompiledCRCProcessor: ...
    @property
    def polynomial(self) -> CRCType: ...
    @property
    def initial_crc_value(self) -> CRCType: ...
    @property
    def final_xor_value(self) -> CRCType: ...
    @property
    def reflected(self) -> bool: ...

class SerialMock:
    is_open: bool
    tx_buffer: bytes
    rx_buffer: bytes
    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...
    def open(self) -> None: ...
    def close(self) -> None: ...
    def write(self, data: bytes) -> None: ...
    def read(self, size: int = 1) -> bytes: ...
    def reset_input_buffer(self) -> None: ...
    def reset_output_buffer(self) -> None: ...
    @property
    def in_waiting(self) -> int: ...
    @property
    def out_waiting(self) -> int: ...

class CompiledCOBSProcessor:
    maximum_payload_size: int
    minimum_payload_size: int
    maximum_packet_size: int
    minimum_packet_size: int
    delimiter: int
    def __init__(self) -> None: ...
    def encode_payload(self, payload: NDArray[np.uint8]) -> NDArray[np.uint8]: ...
    def decode_payload(self, packet: NDArray[np.uint8]) -> NDArray[np.uint8]: ...

class CompiledCRCProcessor:
    polynomial: CRCType
    initial_crc_value: CRCType
    final_xor_value: CRCType
    reflected: bool
    crc_byte_length: np.uint8
    crc_table: Incomplete
    initial_register: CRCType
    expected_residue: CRCType
    def __init__(
        self, polynomial: CRCType, initial_crc_value: CRCType, final_xor_value: CRCType, reflected: bool
    ) -> None: ...
    def calculate_checksum(self, buffer: NDArray[np.uint8], check: bool = False) -> np.uint16: ...
    def _reflect_value(self, value: CRCType) -> CRCType: ...
    def _generate_crc_table(self, polynomial: CRCType) -> None: ...
    def _compute_expected_residue(self) -> CRCType: ...
    def _update_checksum(self, checksum: CRCType, data_byte: np.uint8) -> CRCType: ...
    def _extract_checksum_byte(self, checksum: CRCType, index: int) -> np.uint8: ...
    def _make_polynomial_type(self, value: Any) -> CRCType: ...
