name: general_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - black=24.2.0
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - click=8.1.7
  - colorama=0.4.6
  - coverage=7.4.3
  - exceptiongroup=1.2.0
  - iniconfig=2.0.0
  - intel-openmp=2024.0.0
  - isort=5.13.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libexpat=2.6.1
  - libffi=3.4.2
  - libhwloc=2.9.3
  - libiconv=1.17
  - liblapack=3.9.0
  - libsodium=1.0.18
  - libsqlite=3.45.1
  - libxml2=2.12.5
  - libzlib=1.2.13
  - llvmlite=0.42.0
  - mkl=2024.0.0
  - mypy_extensions=1.0.0
  - numba=0.59.0
  - numpy=1.26.4
  - openssl=3.2.1
  - packaging=24.0
  - pathspec=0.12.1
  - pip=24.0
  - platformdirs=4.2.0
  - pluggy=1.4.0
  - pthreads-win32=2.9.1
  - pyserial=3.5
  - pytest=8.1.1
  - pytest-cov=4.1.0
  - python=3.11.8
  - python_abi=3.11
  - pyzmq=25.1.2
  - setuptools=69.1.1
  - tbb=2021.11.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - tqdm=4.66.2
  - tzdata=2024a
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.38.33130
  - vs2015_runtime=14.38.33130
  - wheel=0.42.0
  - xz=5.2.6
  - zeromq=4.3.5
